### ISSUE TITLE
Add ID to nav items

### ISSUE THREAD

**Issue by alecalve** [BitMEXResearch/forkmonitor#1]
Currently, the nav items allowing switching between Bitcoin and Bitcoin Cash don't have IDs. This make it impossible to link to the BCH tab directly, you have to manually click on it.

**Comment by Sjors** [comment]
Thanks. I need to read up on ReactJS routing, but it's probably a trivial change to make /#/btc and /#/bch work.

**Comment by Sjors** [comment]
Fixed in 989d1e2edb5b180f94c3c00d67b22486ae2d69f1, should be live in a moment.

**Comment by nwlezien** [comment]
@alecalve I have a question but I cannot ask you directly. Does your blockchain-parser.py program take into account all issues (Including orphan blocks)? This is only referring to the get_unordered_blocks (Since this is the only one I use. Thanks, there is no other way to find out.
