### ISSUE TITLE
Alerts for invalid mainnet blocks with sufficient proof of work

### ISSUE THREAD

**Issue by Sjors** [BitMEXResearch/forkmonitor#101]
Even if all nodes consider it invalid. Should be a seperate feed.

**Comment by BitMEXResearch** [comment]
> Even if all nodes consider it **in**valid.  ?

**Comment by Sjors** [comment]
Done in 309d000b15b5ba2b2f8c24d51c38eddd056f773f and a873d97ded434fd2a7d2b0d6a0da5b2efe1777dd.
