### ISSUE TITLE
Lightning page features

### ISSUE THREAD

**Issue by BitMEXResearch** [BitMEXResearch/forkmonitor#109]
1. Rank entire by date, most recent at the top
2. Wrap the TXID so that it spans multiple lines on mobile
3. Show input value for penalty transactions
4. Perhaps a live line chart, time on X axis and weekly penalty transaction input value on the Y axis (or something more clever)
5. Can the lightning strike logo be yellow?
6. Mention the version of Bitcoin Core generating these results on the page

**Comment by Sjors** [comment]
Re 2: I made the table scrollable and a bit more compact e183dde88ba807731f59b3ae8c022aa0069fc093
Re 3: I'm using the output value instead 786c6313991629893cbb8fda4eba5ce417b8bc10
Re 4: made a separate issue #114
Re 5: done in 01acda7de4002c8f1ca4f9e732e829fcc8f11442 (using orange, yellow is almost invisible on a white background)
Re 6: we're not currently tracking that
