### ISSUE TITLE
Penalty Transactions Page

### ISSUE THREAD

**Issue by BitMEXResearch** [BitMEXResearch/forkmonitor#116]
Maybe at the top add:

- Total number of Penalty Transactions: XX
- Total BTX: XX.XXX

**Comment by Sjors** [comment]
I didn't like the aesthetics of this:
<img width="428" alt="Schermafbeelding 2019-12-17 om 13 40 14" src="https://user-images.githubusercontent.com/10217/70996309-c5aea700-20d2-11ea-8e00-8a4f466dfc74.png">

So I put in the header instead, similar to what we do with block hash:

<img width="958" alt="Schermafbeelding 2019-12-17 om 13 43 59" src="https://user-images.githubusercontent.com/10217/70996545-4bcaed80-20d3-11ea-9d6b-f7bd6f27f754.png">
