### ISSUE TITLE
Bug - TX Index control doesnt match output

### ISSUE THREAD

**Issue by BitMEXResearch** [BitMEXResearch/forkmonitor#119]
The control says Core 0.16.2 has TX Index off

<img width="466" alt="Untitled" src="https://user-images.githubusercontent.com/42411042/71363521-584abc80-2591-11ea-8e81-f2fd20674075.png">

Yet the website indicates TX index is on

**Comment by Sjors** [comment]
The admin panel value is correct, the display on the site is wrong. Fixed by 0eb50f0a703181a8604150b24f88077f7804e92e.
