### ISSUE TITLE
Development setup - unable to proceed past database migration

### ISSUE THREAD

**Issue by losh11** [BitMEXResearch/forkmonitor#181]
Followed DEVELOPMENT.md and attempting to run forkmonitor locally. I've started the server using `foreman`, and opened up 'localhost:3000' in the browser. React app shows error message showing that database migrations are pending, and there's a button which runs migrations. Pressing the button runs a couple of migrations, but `add_coin_to_orphan_candidate.rb` eventually fails with error: 

```
An error has occurred, this and all later migrations canceled:
uninitialized constant AddCoinToOrphanCandidate::OrphanCandidate
```

![](https://i.imgur.com/hCaBTuw.png)

**Comment by Sjors** [comment]
@losh11 I see there's a step missing in the instructions. Try `bundle exec rake db:schema:load`. This should load the database structure in one go. 

Migrations are incremental. It's possible that they don't work all the way through due to various refactoring.

**Comment by losh11** [comment]
Yep that seems to fix it!
