### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by BitMEXResearch** [BitMEXResearch/forkmonitor#31]
- Make the hash go onto multiple lines when the screen is narrow, such that the site looks good on mobile
- Change height number format from 573212 to 573,212
- Change time format from 2019-04-25 20:00 to 2019-04-25 20:00:00 UTC

**Comment by Sjors** [comment]
Using CSS ellipses instead (copy-paste still works):
<img width="585" alt="Schermafbeelding 2019-04-29 om 11 18 09" src="https://user-images.githubusercontent.com/10217/56886969-8b739500-6a70-11e9-9fac-af2aa4a8bcf5.png">
