### ISSUE TITLE
Chaintip section features

### ISSUE THREAD

**Issue by BitMEXResearch** [BitMEXResearch/forkmonitor#33]
- Add Blocksize to the chaintip section. Format "Latest blocksize: 1.2MB"
- Add TX count to the chaintip section. Format "Latest block transaction count: 1,572"

**Comment by Sjors** [comment]
Done in 327711b992fd4ca5f8fa222fc61e35863f363768 and e25f400b5a9414f976a399e5256bc7d125eb0803
<img width="788" alt="Schermafbeelding 2019-07-08 om 15 26 54" src="https://user-images.githubusercontent.com/10217/60818104-e1616900-a194-11e9-8562-9cbad0a7a427.png">
