### ISSUE TITLE
Bitcoin Cash features

### ISSUE THREAD

**Issue by BitMEXResearch** [BitMEXResearch/forkmonitor#34]
- Split the Bitcoin Cash tab into Bitcoin Cash ABC and Bitcoin Cash SV

- Implement the same features for the Bitcoin Cash ABC and Bitcoin Cash SV side as we have for Bitcoin if possible

**Comment by Sjors** [comment]
This will be easier if I can get rid of the last common block and estimated cost of mining since the split stuff.
<img width="909" alt="Schermafbeelding 2019-04-29 om 11 40 10" src="https://user-images.githubusercontent.com/10217/56888115-8fed7d00-6a73-11e9-8242-2107cb5152c0.png">

**Comment by BitMEXResearch** [comment]
Yeah. Sounds fine
