### ISSUE TITLE
New Favicon

### ISSUE THREAD

**Issue by BitMEXResearch** [BitMEXResearch/forkmonitor#45]
![favicon-32x32](https://user-images.githubusercontent.com/42411042/57945010-a186af80-78d0-11e9-9b2e-a29b6da1e345.png)

**Comment by BitMEXResearch** [comment]
![favicon-32x32](https://user-images.githubusercontent.com/42411042/58817768-5f75a180-8624-11e9-8e1b-ebc1b22c32da.png)

Larger improved favicon image

**Comment by BitMEXResearch** [comment]
![favicon-32x32 (1)](https://user-images.githubusercontent.com/42411042/58818925-f2174000-8626-11e9-97b6-021a8e266c20.png)
Even better logo

**Comment by Sjors** [comment]
Added for all device types in #56.
