### ISSUE TITLE
New website logo

### ISSUE THREAD

**Issue by BitMEXResearch** [BitMEXResearch/forkmonitor#55]
![Fork Monitor Masthead Logo](https://user-images.githubusercontent.com/42411042/58818960-052a1000-8627-11e9-82d7-95ef0556e225.png)

**Comment by Sjors** [comment]
Looks like you succesfully added this in 41cbf046a6587fcfe9f7354fbf1dad74dd8ea456 and f9104d4d58603a2e86ee4d04302f40aa57cae89c.

In 76378378f1eb2e4e172833813f5ceadf24d5ca47 I copied the image into the repository, which should be a better experience than loading it from an external site.
