### ISSUE TITLE
Inflation Check display

### ISSUE THREAD

**Issue by BitMEXResearch** [BitMEXResearch/forkmonitor#81]
Can we display the inflation check using something like this?

<img width="1836" alt="Screenshot 2019-10-10 at 13 33 40" src="https://user-images.githubusercontent.com/42411042/66569476-8cead280-eb63-11e9-9aa6-bd1b1abad7e1.png">

On hover over the red cross it could tell us which block the unexpected inflation  occurred at and how much

Unexpected inflation would also trigger a red warning banner at the top. 

Unexpected deflation could have a small image like this

![image](https://user-images.githubusercontent.com/42411042/66569533-adb32800-eb63-11e9-85f7-55447c3c027a.png)

Also is there a concept/problem of non-matching coin supply at the same height? Should that trigger some kind of alert?

**Comment by Sjors** [comment]
Moving deflation to #84

**Comment by Sjors** [comment]
An inflation banner was added in #77

**Comment by Sjors** [comment]
> Also is there a concept/problem of non-matching coin supply at the same height? Should that trigger some kind of alert?

Moved to #85

**Comment by Sjors** [comment]
I made a seperate issue to add the expected inflation to a hover: #86
