### ISSUE TITLE
Inflation popup - Show message even in normal case

### ISSUE THREAD

**Issue by BitMEXResearch** [BitMEXResearch/forkmonitor#93]
Display as follows:

- Coin Supply: XX,XXX,XXX.X
- Expected Coin Supply: XX,XXX.X
- Change from previous block: XX.X
- Expected Change: XX.X
- Block Height: XXX,XXX

**Comment by Sjors** [comment]
Partial duplicate of #86

**Comment by Sjors** [comment]
In case inflation check is lagging, I can also show the current block height that's being checked in the popup under the spinner.

**Comment by Sjors** [comment]
<img width="949" alt="Schermafbeelding 2020-05-06 om 16 40 49" src="https://user-images.githubusercontent.com/10217/81190619-5c173280-8fb8-11ea-895a-2d39dd062d77.png">
